name: tests

on:
  push:
    branches: [ rest, grpc ]
  pull_request:
    branches: [ rest, grpc ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install protoc
      run: sudo apt install -y protobuf-compiler

    - name: Install the Go protocol buffers plugin
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Generate code from .proto
      run: make protos

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -covermode=atomic -shuffle=on -coverprofile=coverage.out -v ./...

    - name: Upload coverage to codeclimate
      uses: paambaati/codeclimate-action@v3.0.0
      continue-on-error: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
      with:
        coverageCommand: ''
        prefix: 'github.com/brokeyourbike/nickroservices'
        coverageLocations: ./coverage.out:gocov